name: $(Date:yyyyMMdd).$(Rev:.r)
variables:
  - group: Polaris
 
jobs:
- job: Polaris
  pool:
    name: OSIsoft
  workspace:
    clean: all
  steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    clean: true