# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- azure-pipelines

pool:
  name: OSIsoft
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: 'Polaris' # variable group
  msbuildPath: '' # must be initialized to use
  polarisPath: '' # must be initialized to use

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Run vswhere to get msbuild path
      $Env:Path = "C:\Program Files\Microsoft Visual Studio\Installer" + ";" + $Env:Path
      $msbuildPath = vswhere.exe -latest -prerelease -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
      $msbuildPath = $msbuildPath.substring(0,$msbuildPath.indexOf("\MSBuild.exe"))
      echo $msbuildPath
      Write-Output ("##vso[task.setvariable variable=msbuildPath;]${msbuildPath}")

