# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- azure-pipelines

pool:
  name: OSIsoft
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Download and run vswhere to get msbuild path
      $uri = "https://github.com/Microsoft/vswhere/releases/latest/download/vswhere.exe"
      Invoke-WebRequest -Uri $uri -OutFile "vswhere.exe"
