# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool: 
  name: OSIsoft
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # MPB Add the following global variables
  group: 'Polaris' # variable group
  msbuildPath: '' # must be initialized to use
  polarisPath: '' # must be initialized to use

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  displayName: Find MSbuild Path
  inputs:
    targetType: 'inline'
    script: |
      Set-PSDebug -Trace 1
      # Download and run vswhere to get msbuild path
      $cmd = "C:\Program Files\\Microsoft Visual Studio\Installer\vswhere.exe -latest -prerelease -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe"
      Invoke-Expression $cmd
      #$msbuildPath = 'C:\Program Files\\Microsoft Visual Studio\Installer\vswhere.exe' -latest -prerelease -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
      $msbuildPath = $msbuildPath.substring(0,$msbuildPath.indexOf("\MSBuild.exe"))
      echo $pwd
      Write-Output ("##vso[task.setvariable variable=msbuildPath;]${msbuildPath}")
      echo $env:MSBUILDPATH
